// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBRAkx3gmpWzMfSWggSwLzX3_Dwo5_K4',
    appId: '1:37822407427:web:231d99340dbba6ad1dff36',
    messagingSenderId: '37822407427',
    projectId: 'chatapp-24753',
    authDomain: 'chatapp-24753.firebaseapp.com',
    storageBucket: 'chatapp-24753.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_vwJ__jXDdTSG6y05Ub9Fj8GAXkVCEHk',
    appId: '1:37822407427:android:03acce4c98a9f3981dff36',
    messagingSenderId: '37822407427',
    projectId: 'chatapp-24753',
    storageBucket: 'chatapp-24753.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBRAkx3gmpWzMfSWggSwLzX3_Dwo5_K4',
    appId: '1:37822407427:web:bbea577ecdc6bfcb1dff36',
    messagingSenderId: '37822407427',
    projectId: 'chatapp-24753',
    authDomain: 'chatapp-24753.firebaseapp.com',
    storageBucket: 'chatapp-24753.appspot.com',
  );
}
